/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    projects: Project;
    career: Career;
    testimonials: Testimonial;
    playground: Playground;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    career: CareerSelect<false> | CareerSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    playground: PlaygroundSelect<false> | PlaygroundSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    design: Design;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    design: DesignSelect<false> | DesignSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  shell?:
    | (
        | 'portfolio-shell'
        | 'inner-page'
        | 'inner-page work-page work-page-detailed'
        | 'inner-page playground-page'
        | 'contact-page'
      )
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  sections: (
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        layout?: ('centered' | 'split') | null;
        image?: (number | null) | Media;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image: number | Media;
        side?: ('left' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        layout?: ('grid' | 'list') | null;
        items?:
          | {
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'capabilities';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        layout?: ('grid' | 'list') | null;
        projects: (number | Project)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'projects';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        entries: (number | Career)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        layout?: ('grid' | 'list') | null;
        entries: (number | Testimonial)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'quotes';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        layout?: ('grid' | 'list') | null;
        entries: (number | Playground)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'playground';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        tone?: ('light' | 'dark' | 'paper') | null;
        project: number | Project;
        variant?: ('home' | 'work') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectPresentation';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        field8?: string | null;
        field9?: string | null;
        field10?: string | null;
        field11?: string | null;
        field12?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeSection1';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        field8?: string | null;
        field9?:
          | {
              icon?: ('Layers3' | 'Smartphone' | 'Users2') | null;
              number?: string | null;
              title?: string | null;
              copy?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeSection5';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeSection6';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeSection7';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field4?: string | null;
        field5?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeSection8';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field6?: (number | null) | Media;
        field7?: string | null;
        field8?: (number | null) | Media;
        field9?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutSection1';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field5?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutSection2';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        field8?: string | null;
        field9?: string | null;
        field10?: string | null;
        field11?: string | null;
        field12?: string | null;
        field13?: string | null;
        field14?: string | null;
        field15?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutSection3';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?:
          | {
              column1?: string | null;
              column2?: string | null;
              column3?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutSection4';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workSection1';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        projects?: (number | Project)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workSection2';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        field8?: string | null;
        field9?: string | null;
        field10?: string | null;
        field11?: string | null;
        field12?: string | null;
        field13?: string | null;
        field14?: string | null;
        field15?: string | null;
        field16?: string | null;
        field17?: string | null;
        field18?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workSection3';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        field7?: string | null;
        field8?: string | null;
        field9?: string | null;
        field10?: string | null;
        field11?: string | null;
        field12?:
          | {
              number?: string | null;
              icon?: ('Users2' | 'Code2' | 'Presentation' | 'Rocket') | null;
              title?: string | null;
              copy?: string | null;
              tags?:
                | {
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workSection4';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field3?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workSection5';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        field6?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactSection1';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        field4?: string | null;
        field5?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'playgroundSection1';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'playgroundSection2';
      }
    | {
        hidden?: boolean | null;
        /**
         * Optional section ID for navigation links.
         */
        anchor?: string | null;
        field1?: string | null;
        field2?: string | null;
        field3?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'playgroundSection3';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  sourcePath?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  role?: string | null;
  category?: string | null;
  technologies?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  presentations?:
    | (
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field1?: string | null;
            field2?: string | null;
            field3?: string | null;
            field5?: string | null;
            field6?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            field7?: string | null;
            field8?: string | null;
            field9?: string | null;
            field10?: string | null;
            field11?: string | null;
            field12?:
              | {
                  value?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            field13?: string | null;
            field14?: string | null;
            field15?: string | null;
            field16?: string | null;
            field17?: string | null;
            field18?: string | null;
            field19?: string | null;
            field20?: string | null;
            field21?: string | null;
            field22?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSection2';
          }
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field1?: string | null;
            field2?: string | null;
            field3?: string | null;
            field5?: string | null;
            field6?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            field7?: string | null;
            field8?: string | null;
            field9?: string | null;
            field10?: string | null;
            field11?: string | null;
            field12?: string | null;
            field13?:
              | {
                  value?: string | null;
                  label?: string | null;
                  id?: string | null;
                }[]
              | null;
            field14?: string | null;
            field15?: string | null;
            field16?: string | null;
            field17?: string | null;
            field18?: string | null;
            field19?: string | null;
            field20?: string | null;
            field21?: string | null;
            field22?: string | null;
            field23?: string | null;
            field24?: string | null;
            field25?: string | null;
            field26?: string | null;
            field27?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSection3';
          }
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field1?: string | null;
            field2?: string | null;
            field3?: string | null;
            field5?: string | null;
            field6?: string | null;
            field7?:
              | {
                  value: string;
                  id?: string | null;
                }[]
              | null;
            field8?: string | null;
            field9?: string | null;
            field10?: string | null;
            field11?: string | null;
            field12?: string | null;
            field13?: string | null;
            field14?: string | null;
            field15?: string | null;
            field16?: string | null;
            field17?: string | null;
            field18?: string | null;
            field19?: string | null;
            field20?: string | null;
            field21?: string | null;
            field22?: string | null;
            field23?: string | null;
            field24?: string | null;
            field25?: string | null;
            field26?: string | null;
            field27?: string | null;
            field28?: string | null;
            field29?: string | null;
            field30?: (number | null) | Media;
            field31?: string | null;
            field32?: string | null;
            field33?: string | null;
            field34?: string | null;
            field35?: string | null;
            field36?: string | null;
            field37?: string | null;
            field38?: string | null;
            field39?: string | null;
            field40?: string | null;
            field41?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSection4';
          }
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field3?: string | null;
            field4?: string | null;
            field5?: string | null;
            field7?: string | null;
            field8?: string | null;
            field9?: string | null;
            field10?: string | null;
            field11?: string | null;
            field12?: string | null;
            field13?: string | null;
            field14?: string | null;
            field15?: string | null;
            field16?: string | null;
            field17?: string | null;
            field18?: string | null;
            field19?: string | null;
            field20?: string | null;
            field21?: string | null;
            field22?: string | null;
            field23?: string | null;
            field24?: string | null;
            field25?: string | null;
            field26?: string | null;
            field27?: string | null;
            field28?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'neevWork';
          }
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field29?: string | null;
            field30?: string | null;
            field31?: string | null;
            field33?: string | null;
            field34?: string | null;
            field35?: string | null;
            field36?: string | null;
            field37?: string | null;
            field38?: string | null;
            field39?: string | null;
            field40?: string | null;
            field41?: string | null;
            field42?: string | null;
            field43?: string | null;
            field44?: string | null;
            field45?: string | null;
            field46?: string | null;
            field47?: string | null;
            field48?: string | null;
            field49?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'evaluationWork';
          }
        | {
            hidden?: boolean | null;
            /**
             * Optional section ID for navigation links.
             */
            anchor?: string | null;
            field50?: string | null;
            field51?: string | null;
            field52?: string | null;
            field54?: string | null;
            field55?: string | null;
            field56?: string | null;
            field57?: string | null;
            field58?: string | null;
            field59?: string | null;
            field60?: string | null;
            field61?: string | null;
            field62?: (number | null) | Media;
            field63?: string | null;
            field64?: string | null;
            field65?: string | null;
            field66?: string | null;
            field67?: string | null;
            field68?: string | null;
            field69?: string | null;
            field70?: string | null;
            field71?: string | null;
            field72?: string | null;
            field73?: string | null;
            field74?: string | null;
            field75?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'etalkWork';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career".
 */
export interface Career {
  id: number;
  role: string;
  company?: string | null;
  period?: string | null;
  order?: number | null;
  chapter?: string | null;
  headline?: string | null;
  summary?: string | null;
  homeSummary?: string | null;
  responsibilities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  growth?: string | null;
  icon?: ('Code2' | 'Layers3' | 'Rocket' | 'Users2') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  quote: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground".
 */
export interface Playground {
  id: number;
  title: string;
  description?: string | null;
  demo:
    | 'MemoryGameModal'
    | 'TicTacToeModal'
    | 'SnakeGameModal'
    | 'Game2048Modal'
    | 'SimonSaysModal'
    | 'TowerOfHanoiModal'
    | 'PathfindingModal'
    | 'SortingModal'
    | 'BSTModal'
    | 'NQueensModal'
    | 'MazeModal'
    | 'EventLoopModal'
    | 'PromiseModal';
  category: 'game' | 'system';
  order?: number | null;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'career';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'playground';
        value: number | Playground;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shell?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              layout?: T;
              image?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              body?: T;
              image?: T;
              side?: T;
              id?: T;
              blockName?: T;
            };
        capabilities?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              layout?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              layout?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              entries?: T;
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              layout?: T;
              entries?: T;
              id?: T;
              blockName?: T;
            };
        playground?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              layout?: T;
              entries?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectPresentation?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              tone?: T;
              project?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        homeSection1?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              id?: T;
              blockName?: T;
            };
        homeSection5?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?:
                | T
                | {
                    icon?: T;
                    number?: T;
                    title?: T;
                    copy?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeSection6?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              id?: T;
              blockName?: T;
            };
        homeSection7?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              id?: T;
              blockName?: T;
            };
        homeSection8?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field4?: T;
              field5?: T;
              id?: T;
              blockName?: T;
            };
        aboutSection1?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              id?: T;
              blockName?: T;
            };
        aboutSection2?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field5?: T;
              id?: T;
              blockName?: T;
            };
        aboutSection3?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              field13?: T;
              field14?: T;
              field15?: T;
              id?: T;
              blockName?: T;
            };
        aboutSection4?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?:
                | T
                | {
                    column1?: T;
                    column2?: T;
                    column3?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        workSection1?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              id?: T;
              blockName?: T;
            };
        workSection2?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        workSection3?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              field13?: T;
              field14?: T;
              field15?: T;
              field16?: T;
              field17?: T;
              field18?: T;
              id?: T;
              blockName?: T;
            };
        workSection4?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?:
                | T
                | {
                    number?: T;
                    icon?: T;
                    title?: T;
                    copy?: T;
                    tags?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        workSection5?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field3?: T;
              id?: T;
              blockName?: T;
            };
        contactSection1?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field6?: T;
              id?: T;
              blockName?: T;
            };
        playgroundSection1?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              id?: T;
              blockName?: T;
            };
        playgroundSection2?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              id?: T;
              blockName?: T;
            };
        playgroundSection3?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  role?: T;
  category?: T;
  technologies?:
    | T
    | {
        value?: T;
        id?: T;
      };
  image?: T;
  presentations?:
    | T
    | {
        homeSection2?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field5?: T;
              field6?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              field13?: T;
              field14?: T;
              field15?: T;
              field16?: T;
              field17?: T;
              field18?: T;
              field19?: T;
              field20?: T;
              field21?: T;
              field22?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeSection3?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field5?: T;
              field6?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              field13?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              field14?: T;
              field15?: T;
              field16?: T;
              field17?: T;
              field18?: T;
              field19?: T;
              field20?: T;
              field21?: T;
              field22?: T;
              field23?: T;
              field24?: T;
              field25?: T;
              field26?: T;
              field27?: T;
              id?: T;
              blockName?: T;
            };
        homeSection4?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field1?: T;
              field2?: T;
              field3?: T;
              field5?: T;
              field6?: T;
              field7?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              field13?: T;
              field14?: T;
              field15?: T;
              field16?: T;
              field17?: T;
              field18?: T;
              field19?: T;
              field20?: T;
              field21?: T;
              field22?: T;
              field23?: T;
              field24?: T;
              field25?: T;
              field26?: T;
              field27?: T;
              field28?: T;
              field29?: T;
              field30?: T;
              field31?: T;
              field32?: T;
              field33?: T;
              field34?: T;
              field35?: T;
              field36?: T;
              field37?: T;
              field38?: T;
              field39?: T;
              field40?: T;
              field41?: T;
              id?: T;
              blockName?: T;
            };
        neevWork?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field3?: T;
              field4?: T;
              field5?: T;
              field7?: T;
              field8?: T;
              field9?: T;
              field10?: T;
              field11?: T;
              field12?: T;
              field13?: T;
              field14?: T;
              field15?: T;
              field16?: T;
              field17?: T;
              field18?: T;
              field19?: T;
              field20?: T;
              field21?: T;
              field22?: T;
              field23?: T;
              field24?: T;
              field25?: T;
              field26?: T;
              field27?: T;
              field28?: T;
              id?: T;
              blockName?: T;
            };
        evaluationWork?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field29?: T;
              field30?: T;
              field31?: T;
              field33?: T;
              field34?: T;
              field35?: T;
              field36?: T;
              field37?: T;
              field38?: T;
              field39?: T;
              field40?: T;
              field41?: T;
              field42?: T;
              field43?: T;
              field44?: T;
              field45?: T;
              field46?: T;
              field47?: T;
              field48?: T;
              field49?: T;
              id?: T;
              blockName?: T;
            };
        etalkWork?:
          | T
          | {
              hidden?: T;
              anchor?: T;
              field50?: T;
              field51?: T;
              field52?: T;
              field54?: T;
              field55?: T;
              field56?: T;
              field57?: T;
              field58?: T;
              field59?: T;
              field60?: T;
              field61?: T;
              field62?: T;
              field63?: T;
              field64?: T;
              field65?: T;
              field66?: T;
              field67?: T;
              field68?: T;
              field69?: T;
              field70?: T;
              field71?: T;
              field72?: T;
              field73?: T;
              field74?: T;
              field75?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career_select".
 */
export interface CareerSelect<T extends boolean = true> {
  role?: T;
  company?: T;
  period?: T;
  order?: T;
  chapter?: T;
  headline?: T;
  summary?: T;
  homeSummary?: T;
  responsibilities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  growth?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground_select".
 */
export interface PlaygroundSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  demo?: T;
  category?: T;
  order?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourcePath?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  description?: string | null;
  email: string;
  location?: string | null;
  availability?: string | null;
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  contactHref?: string | null;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seoImage?: (number | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design".
 */
export interface Design {
  id: number;
  light: {
    background: string;
    foreground: string;
    paper: string;
    ink: string;
    accent: string;
    warmAccent: string;
  };
  dark: {
    background: string;
    foreground: string;
    paper: string;
    ink: string;
    accent: string;
    warmAccent: string;
  };
  font?: ('current' | 'sans' | 'serif') | null;
  defaultTheme?: ('system' | 'light' | 'dark') | null;
  textScale?: number | null;
  contentWidth?: number | null;
  spacing?: number | null;
  radius?: number | null;
  motion?: ('full' | 'reduced') | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  email?: T;
  location?: T;
  availability?: T;
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactLabel?: T;
  contactHref?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seoImage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design_select".
 */
export interface DesignSelect<T extends boolean = true> {
  light?:
    | T
    | {
        background?: T;
        foreground?: T;
        paper?: T;
        ink?: T;
        accent?: T;
        warmAccent?: T;
      };
  dark?:
    | T
    | {
        background?: T;
        foreground?: T;
        paper?: T;
        ink?: T;
        accent?: T;
        warmAccent?: T;
      };
  font?: T;
  defaultTheme?: T;
  textScale?: T;
  contentWidth?: T;
  spacing?: T;
  radius?: T;
  motion?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}